{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ba9d221e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome to TechMate!\n",
      "\n",
      "Choose a topic:\n",
      "1. Artificial Intelligence\n",
      "2. Blockchain\n",
      "3. Cybersecurity\n",
      "4. FinTech\n",
      "5. How to Learn Digital Skills\n",
      "6. Exit\n",
      "Enter your choice (1-6): 1\n",
      "AI simulates human intelligence with machines.\n",
      "\n",
      "Choose a topic:\n",
      "1. Artificial Intelligence\n",
      "2. Blockchain\n",
      "3. Cybersecurity\n",
      "4. FinTech\n",
      "5. How to Learn Digital Skills\n",
      "6. Exit\n",
      "Enter your choice (1-6): 5\n",
      "You can learn digital skills on Coursera, edX, or YouTube.\n",
      "\n",
      "Choose a topic:\n",
      "1. Artificial Intelligence\n",
      "2. Blockchain\n",
      "3. Cybersecurity\n",
      "4. FinTech\n",
      "5. How to Learn Digital Skills\n",
      "6. Exit\n",
      "Enter your choice (1-6): 3\n",
      "Cybersecurity protects your digital assets.\n",
      "\n",
      "Choose a topic:\n",
      "1. Artificial Intelligence\n",
      "2. Blockchain\n",
      "3. Cybersecurity\n",
      "4. FinTech\n",
      "5. How to Learn Digital Skills\n",
      "6. Exit\n",
      "Enter your choice (1-6): 4\n",
      "FinTech uses tech to improve financial services.\n",
      "\n",
      "Choose a topic:\n",
      "1. Artificial Intelligence\n",
      "2. Blockchain\n",
      "3. Cybersecurity\n",
      "4. FinTech\n",
      "5. How to Learn Digital Skills\n",
      "6. Exit\n",
      "Enter your choice (1-6): 6\n",
      "Goodbye!\n"
     ]
    }
   ],
   "source": [
    "def show_menu():\n",
    "    print(\"\\nChoose a topic:\")\n",
    "    print(\"1. Artificial Intelligence\")\n",
    "    print(\"2. Blockchain\")\n",
    "    print(\"3. Cybersecurity\")\n",
    "    print(\"4. FinTech\")\n",
    "    print(\"5. How to Learn Digital Skills\")\n",
    "    print(\"6. Exit\")\n",
    "\n",
    "def handle_choice(choice):\n",
    "    if choice == '1':\n",
    "        return \"AI simulates human intelligence with machines.\"\n",
    "    elif choice == '2':\n",
    "        return \"Blockchain is a secure digital ledger used for transactions.\"\n",
    "    elif choice == '3':\n",
    "        return \"Cybersecurity protects your digital assets.\"\n",
    "    elif choice == '4':\n",
    "        return \"FinTech uses tech to improve financial services.\"\n",
    "    elif choice == '5':\n",
    "        return \"You can learn digital skills on Coursera, edX, or YouTube.\"\n",
    "    elif choice == '6':\n",
    "        return \"Goodbye!\"\n",
    "    else:\n",
    "        return \"Invalid choice.\"\n",
    "\n",
    "def main():\n",
    "    print(\"Welcome to TechMate!\")\n",
    "    while True:\n",
    "        show_menu()\n",
    "        choice = input(\"Enter your choice (1-6): \")\n",
    "        response = handle_choice(choice)\n",
    "        print(response)\n",
    "        if choice == '6':\n",
    "            break\n",
    "\n",
    "main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "688c1671",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
